# Generated by Django 4.0.4 on 2022-07-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('club', models.CharField(max_length=30)),
                ('exjug', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('liga', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('estadio', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=20)),
                ('pie', models.CharField(max_length=12)),
                ('edad', models.IntegerField()),
                ('club', models.CharField(max_length=30)),
                ('dorsal', models.IntegerField(max_length=3)),
            ],
        ),
    ]
